# NumPy Basics




In [1]:
import numpy as np


In [2]:
mylist=[1,2,3]

In [4]:
type(mylist)


list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
myArray=np.array(mylist)
print(myArray)


[1 2 3]


In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
myMatrix=np.array(my_matrix)
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
np.arange(1,4)

array([1, 2, 3])

In [11]:
np.arange(1,6,2)

array([1, 3, 5])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(3,3)

array([[0.1435475 , 0.68663581, 0.23885769],
       [0.31868432, 0.98696113, 0.88422788],
       [0.98025352, 0.54121986, 0.77542897]])

In [20]:
np.random.randn(3,3)

array([[ 0.30150236, -0.53721302,  1.28091771],
       [-0.99625151,  0.76615635,  0.1655131 ],
       [ 0.42521051,  0.11532213, -0.60228062]])

In [21]:
np.random.randint(0,101,5)

array([11, 24, 73, 63,  5])

In [22]:
np.random.randint(0,101,(3,3))

array([[ 26,  16,  70],
       [  4,  68,  83],
       [ 70,  33, 100]])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr= np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [31]:
arr.reshape(5,5)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [38]:
ranarr= np.random.randint(0,101,10)
print(ranarr)

[57 21 88 48 90 58 41 91 59 79]


In [33]:
ranarr.max()

99

In [35]:
ranarr.min()

2

In [36]:
ranarr.argmax()

5

In [40]:
ranarr.dtype

dtype('int32')

In [41]:
ranarr.shape

(10,)

In [43]:
ranarr.reshape(5,2)

array([[57, 21],
       [88, 48],
       [90, 58],
       [41, 91],
       [59, 79]])

# INDEXING AND SLICING

In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
print(arr[0:5])

[0 1 2 3 4]


In [5]:
print(arr[5:])

[ 5  6  7  8  9 10]


In [7]:
arr[0:5]= 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [8]:
arr=np.arange(0,11)

In [9]:
slice=arr[0:5]

In [12]:
slice[:]=100
print(slice)

[100 100 100 100 100]


In [13]:
print(arr)


[100 100 100 100 100   5   6   7   8   9  10]


In [14]:
arr=np.arange(0,11)

In [15]:
arrCopy=arr.copy()
arrCopy[:]=100
print(arrCopy)

[100 100 100 100 100 100 100 100 100 100 100]


In [16]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr_2d.shape

(3, 3)

In [20]:
arr_2d[0]

array([1, 2, 3])

In [21]:
arr_2d[2]

array([7, 8, 9])

In [23]:
arr_2d[1,1]

5

In [25]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [26]:
arr =np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr >3

In [31]:
bool_arr


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [32]:
arr[bool_arr]


array([ 4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[arr>4]


array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

In [34]:
import numpy as np


In [36]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [39]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr/arr

C:\Users\legion\AppData\Local\Temp\ipykernel_6096\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
1/0

ZeroDivisionError: division by zero

In [43]:
1/arr

C:\Users\legion\AppData\Local\Temp\ipykernel_6096\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
np.log(arr)

C:\Users\legion\AppData\Local\Temp\ipykernel_6096\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [45]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr.sum()


45

In [48]:
arr.mean()


4.5

In [49]:
arr.max()

9

In [50]:
arr.var()

8.25

In [51]:
arr.std()

2.8722813232690143

In [52]:
arr2d = np.arange(0,25).reshape(5,5)

In [53]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr2d.sum()

300

In [55]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [56]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])